services:
  backup:
    build: .
    container_name: backup
    environment:
      - TOKEN=${TOKEN}
      - DOMAIN=${DOMAIN}
    volumes:
      - ~/.config/rclone:/root/.config/rclone
      - .:/app
    restart: "no"
